INSERT INTO Categories (Name, UrlHandle)
VALUES 
    ('C#', 'csharp-articles'),
    ('Angular', 'angular-tutorials'),
    ('.NET Core', 'dotnet-core'),
    ('JavaScript', 'javascript-tutorials'),
    ('TypeScript', 'typescript-tutorials'),
    ('React', 'react-framework'),
    ('Vue.js', 'vue-js-guides'),
    ('Node.js', 'node-js'),
    ('Express.js', 'express-js'),
    ('Python', 'python-programming'),
    ('Django', 'django-framework'),
    ('Flask', 'flask-tutorials'),
    ('Java', 'java-programming'),
    ('Spring Boot', 'spring-boot'),
    ('Kotlin', 'kotlin-development'),
    ('Swift', 'swift-programming'),
    ('PHP', 'php-development'),
    ('Laravel', 'laravel-tutorials'),
    ('Ruby', 'ruby-language'),
    ('Ruby on Rails', 'ruby-on-rails'),
    ('Go', 'go-programming'),
    ('Rust', 'rust-programming'),
    ('SQL', 'sql-database'),
    ('PostgreSQL', 'postgresql'),
    ('MongoDB', 'mongodb-tutorials'),
    ('Firebase', 'firebase'),
    ('Azure', 'azure-cloud'),
    ('AWS', 'aws-cloud'),
    ('Bootstrap', 'bootstrap-css'),
    ('Tailwind CSS', 'tailwind-css');